### ISSUE TITLE
Ticket 3

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-2-arrays-advanced-functions-functions-team11#2]
```[tasklist]
### Tasks
- [ ] Create a products array
- [ ] Use `.map()` to apply VAT
- [ ] Check the results
```
